# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Suck It Up Documentation
site_url: https://l4valamp.github.io/suckitup-docs/
docs_dir: .mkdocs_docs


theme:
  name: material
  palette: 
    scheme: slate
    primary: blue
    accent: deep orange
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-nav # this should be good
  - databaseview
  - roamlinks #this too
  - entity #this is our custom plugin for variables

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
     alternate_style: true
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/entities.js
