# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

nav:
- Home: 
   - "Suck It Up/00 Home/*"
- Features: 
  - "Suck It Up/04 PagesFromTemplates/Features/*"
- Tech: 
  - "Suck It Up/01 Tech/*"
- Art: 
  - "Suck It Up/01 Art/*"
- Design: 
  - "Suck It Up/01 Design/*"


ignore:
  - "*Excalidraw/"
  - "*Templates/"
  - "*Test quickadd/"

sort:
  by: title